version: '3.1'

services:
  db:
    image: postgres:15
    environment:
      # those credentials should match the default values in .env.example
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpwd
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"