# This CI step should spin up a database and then try to startup the Django app

name: "Django CI"

on: [ push, pull_request ]
jobs:
  black:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.6" ]
        os: [ ubuntu-20.04 ] # 20.04 still support python 3.6
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3 # we need v3 because v4 dropped support for python 3.6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Use example env config
        run: |
          cp .env.example .env
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Start database containers
        run: docker-compose -f "docker-compose.yml" up -d
      - name: Start django with instructions copied from readme
        run: |
          python manage.py runserver  # only temporary to debug error messages, break afterwards
          python manage.py migrate
          python manage.py loaddata fixtures.json  # install fixtures of necessary hardcoded model objects
          python manage.py createsuperuser
